### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by Dradon7** [team-abnormals/allurement#13] opened 2021-04-19 23:21 UTC
Using Minecraft 1.16.5, Forge 36.1.4, Abnormal's Core 3.1.1, and Allurement 1.1.1

Issue:
Every ten seconds, a message is printed onto the console that says that the common config file is incorrect and that it is correcting it. I also have 5 duplicates of the config file called 'allurement-common-1.toml.bak,' though fortunately something is stopping it from making more.

Not sure whats going on. I saw a couple other mods having a similar issue a couple months ago, and they slowly all fixed them. Maybe its a forge bug?

I can't really include crash logs, since there isn't a crash. Lemme know if you guys need more information!

**Comment by pm065** [comment] 2021-05-29 07:40
You have log spam? And I thought just the baks were annoying...
I remember seeing somewhere that it was indeed a forge bug, but one that mods could fix independently.
The reason there's only five bak files is probably because Forge deletes any sixth ones that appear. If it wasn't capped, then the config folder would be coated with allurement-common-#.toml.bak and mekanism-tools-#.toml.bak.
So that means it actually DOES make more, but they're deleted instantly.

**Comment by pm065** [comment] 2021-05-29 07:42
Oh, wait, looks like this is actually a duplicate of #9 which has been closed with a commit fixing the issue.
EDIT: Or has it? There's also a commit reverting the commit, but the issue is closed. Hm.

**Comment by Skrinkus** [comment] 2021-06-08 16:40
I'm also having this issue, specifically in Valhelsia 3. Trying to run a server and it keeps looping this warning, stopping the whole thing from actually starting up the server. I'm on Mojave, and several other users have reported this issue in their discord, also stating that they were on Mojave.

**Comment by saglaniharsh** [comment] 2021-06-12 09:43
I'm also having the log spam with issue #9 
Any fixes yet?

**Comment by Speiger** [comment] 2021-08-15 08:33
This is a forge bug not a Mod Bug. (Config basically reads 0 values when this message was displayed (used a debug tool to see what it compares against) causing a false positive).
The only Exception is with arrays. If arrays get reset to their default values after you changed them then you used "define" for "defineInList".

**Comment by bageldotjpg** [comment] 2021-11-10 00:24
Fixed https://www.curseforge.com/minecraft/mc-mods/allurement/files/3520927

**Closed as completed by bageldotjpg** 2021-11-10 00:24 UTC
